phase "Packages"

PACKAGES=(
  adwaita-cursors
  alacritty
  atool
  bat
  bitwarden
  bluetui
  bottom
  brightnessctl
  cava
  chezmoi
  chromium
  clang
  cliphist
  cups
  cups-browsed
  cups-filters
  cups-pdf
  cups-pk-helper
  dgop
  diff-so-fancy
  dms-shell-niri
  docker-compose
  dosfstools
  evince
  exfatprogs
  eza
  fastfetch
  fd
  ffmpegthumbnailer
  firefox-developer-edition
  font-manager
  fontconfig
  fprintd
  fuse2
  fzf
  gdb
  ghostty
  ghostty-nautilus
  gimp
  git-lfs
  github-cli
  glab
  gnome-boxes
  gnome-calculator
  gnome-characters
  gnome-disk-utility
  gnome-keyring
  gnome-themes-extra
  gparted
  grim
  gvfs-mtp
  gvfs-nfs
  gvfs-smb
  hunspell-es_any
  i2c-tools
  imagemagick
  imath
  impala
  imv
  inetutils
  inxi
  iwd
  jq
  just
  jxrlib
  karchive
  kimageformats
  lazygit
  less
  libavif
  libayatana-appindicator
  libheif
  libjxl
  libqalculate
  libraw
  libreoffice-fresh
  libsecret
  libyaml
  lldb
  llvm
  lshw
  luarocks
  man-db
  mariadb-libs
  matugen
  mise
  mpv
  nano
  nautilus
  nautilus-python
  neovim
  networkmanager
  noto-fonts
  noto-fonts-cjk
  noto-fonts-emoji
  nss-mdns
  nvim
  obsidian
  openexr
  openjpeg2
  pipewire
  pipewire-alsa
  pipewire-pulse
  playerctl
  postgresql-libs
  power-profiles-daemon
  python-gobject
  python-poetry-core
  python-terminaltexteffects
  qbittorrent
  qt5-wayland
  qt6-multimedia
  qt6ct
  ripgrep
  ruby
  satty
  sddm
  socat
  steam
  system-config-printer
  systemd
  tesseract
  tesseract-data-eng
  tldr
  tmux
  tree-sitter-cli
  ttf-firacode-nerd
  ttf-ia-writer
  ttf-jetbrains-mono-nerd
  tzupdate
  unzip
  wf-recorder
  whois
  wiremix
  wireplumber
  wl-clipboard
  woff2-font-awesome
  xdg-desktop-portal
  xdg-desktop-portal-gnome
  xdg-desktop-portal-gtk
  xmlstarlet
  xwayland-satellite
  yazi
  zoxide
)

AUR_PKS=(
  brave-bin
  limine-snapper-sync
  localsend-bin
  megasync-bin
  riskie-bin
  roll
  worktrunk-bin
)

info "Installing ${#PACKAGES[@]} packages..."
pacman -S --noconfirm --needed "${PACKAGES[@]}"
info "Official packages installed"

info "Installing ${#AUR_PKS[@]} packages..."
info "Granting temporary passwordless pacman for AUR build..."
echo "$REAL_USER ALL=(ALL) NOPASSWD: /usr/bin/pacman" >/etc/sudoers.d/99-eco-nopasswd
chmod 0440 /etc/sudoers.d/99-eco-nopasswd

sudo -u "$REAL_USER" yay -S --noconfirm --needed "${AUR_PKS[@]}"

info "AUR packages installed"
