### Colors and status bar
# Example: Set status bar to use dynamic background and foreground
set -g status-style "bg=#141218,fg=#faf8ff"
set -g window-status-style "bg=#141218,fg=#9d99a5"
set -g window-status-current-style "bg=#d7c6ff,fg=#141218"
# set -g status-style "bg=#333333 fg=#5eacd3"
# set -g window-status-style "bg=#333333 fg=#5eacd3"
# set -g window-status-current-style "bg=#5eacd3 fg=#333333"
set -g status-left-length 30
set -g status-left "#S | "
# Right side: [current dir] | [date time] | [hostname]
set -g status-right "#[fg=#9d99a5]#{=100:pane_current_path} #[fg=#9d99a5]| %Y-%m-%d %H:%M #[fg=#9d99a5]| #(hostname)"
# set -g status-right "#[fg=#5eacd3]#{=100:pane_current_path} #[fg=#5eacd3]| %Y-%m-%d %H:%M #[fg=#5eacd3]| #(hostname)"

# Vi mode for copy
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
set -ag terminal-overrides ",*:RGB"
set -g base-index 1
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"
set -g detach-on-destroy off
set -g escape-time 0
set -g focus-events on
set -g history-limit 50000
set -g mode-keys vi
set -g mouse on
set -g pane-base-index 1
set -g renumber-windows on
set -s escape-time 0
setw -g aggressive-resize on
setw -g mode-keys vi
setw -g pane-base-index 1


### Wayland + opencode fixes (CRITICAL)
set -g allow-passthrough on
set-option -g extended-keys on
set -as terminal-features ',xterm-kitty:extkeys'  # Kitty

### Bitwarden SSH agent
set-environment -g SSH_AUTH_SOCK "$HOME/.bitwarden-ssh-agent.sock"

### Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"


### Vim-like pane movement
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r ^ last-window

### Vim-like pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

### Vim-like splits and tree
bind v split-window -v
bind s split-window -h

bind-key b choose-tree -s
# bind b last-window -s

### Quick scripts
bind -r f run-shell "tmux neww eco-tmux-sessionizer"
